# Generated by Django 5.1.3 on 2024-12-05 19:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gallery_promotion_service_sitesettings_teammember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image À propos'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image Hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Photo'),
        ),
    ]
